/* Expressões comuns (chunks) EN -> PT, para destacar em verde no Modo Aprender.
   Ordenar por palavras em ordem decrescente para casar primeiro os maiores. */
const CHUNKS = [
  { en: 'once upon a time', pt: 'era uma vez', note: 'Abertura clássica de contos de fada.' },
  { en: 'happily ever after', pt: 'felizes para sempre', note: 'Fecho clássico de histórias (and they lived happily ever after).' },
  { en: 'a long time ago', pt: 'há muito tempo atrás', note: 'Também abre histórias: a long time ago in a galaxy far, far away.' },
  { en: 'you\'re welcome', pt: 'de nada', note: 'Resposta a thank you.' },
  { en: 'how are you', pt: 'como você está?', note: 'Saudação mais comum.' },
  { en: 'what do you mean', pt: 'o que você quer dizer?' },
  { en: 'I love you', pt: 'eu te amo' },
  { en: 'I don\'t know', pt: 'eu não sei' },
  { en: 'I don\'t care', pt: 'não ligo / tanto faz' },
  { en: 'you are my', pt: 'você é meu/minha' },
  { en: 'just like a', pt: 'bem como um/uma' },
  { en: 'let it go', pt: 'deixa pra lá / solta isso', note: 'Herói de Frozen: desapegar.' },
  { en: 'that\'s right', pt: 'isso mesmo' },
  { en: 'all right', pt: 'tudo bem / beleza' },
  { en: 'no problem', pt: 'sem problema' },
  { en: 'of course', pt: 'é claro' },
  { en: 'thank you', pt: 'obrigado(a)' },
  { en: 'thank you for', pt: 'obrigado por' },
  { en: 'good night', pt: 'boa noite' },
  { en: 'good morning', pt: 'bom dia' },
  { en: 'little star', pt: 'estrelinha', note: 'twinkle, twinkle, little star.' },
  { en: 'come on', pt: 'vamos lá / fala sério' },
  { en: 'wake up', pt: 'acorde' },
  { en: 'look at', pt: 'olhe para' },
  { en: 'look out', pt: 'cuidado' },
  { en: 'so long', pt: 'até logo', note: 'Despedida informal: so long, farewell.' },
  { en: 'far away', pt: 'bem longe' },
  { en: 'every day', pt: 'todo dia' },
  { en: 'right now', pt: 'agora mesmo' },
  { en: 'right away', pt: 'imediatamente / já já' },
  { en: 'a lot of', pt: 'muito(s) / uma porção de' },
  { en: 'kind of', pt: 'meio que / mais ou menos' },
  { en: 'in the world', pt: 'no mundo, em todo lugar' },
  { en: 'find out', pt: 'descobrir' },
  { en: 'give up', pt: 'desistir' },
  { en: 'take care', pt: 'cuide-se' },
  { en: 'hang on', pt: 'espere aí' },
  { en: 'hold on', pt: 'espere / aguente' },
  { en: 'go to sleep', pt: 'ir dormir' },
  { en: 'good luck', pt: 'boa sorte' },
  { en: 'play with', pt: 'brincar com' },
  { en: 'turn around', pt: 'virar / dar meia-volta' },
  { en: 'all together', pt: 'todos juntos' },
  { en: 'a little bit', pt: 'um pouquinho' },
  { en: 'over and over', pt: 'repetidamente' },
  { en: 'up and down', pt: 'para cima e para baixo' },
  { en: 'round and round', pt: 'em volta e volta' },
  { en: 'here we go', pt: 'lá vamos nós' },
  { en: 'there you go', pt: 'aí está / assim que se faz' },
  { en: 'see you later', pt: 'até mais' },
  { en: 'what is this', pt: 'o que é isso?' }
];

CHUNKS.sort((a, b) => b.en.split(' ').length - a.en.split(' ').length);